# Generated by Django 4.2.4 on 2023-08-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_network',
            name='facebook',
            field=models.URLField(verbose_name='Ссылка на facebook'),
        ),
        migrations.AlterField(
            model_name='social_network',
            name='instagram',
            field=models.URLField(verbose_name='Ссылка на instagram'),
        ),
        migrations.AlterField(
            model_name='social_network',
            name='whatsapp',
            field=models.URLField(verbose_name='Ссылка на WhatsApp'),
        ),
    ]
