# Generated by Django 4.2.4 on 2023-08-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_umka_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umka',
            name='name_site',
        ),
        migrations.AddField(
            model_name='umka',
            name='logo_site',
            field=models.ImageField(default=1, upload_to='', verbose_name='Логотип сайта'),
            preserve_default=False,
        ),
    ]
