# Generated by Django 4.2.4 on 2023-08-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
