# Generated by Django 4.2.4 on 2023-08-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_about', models.CharField(max_length=100, verbose_name='Заголовок текста')),
                ('text_about', models.TextField(max_length=500, verbose_name='Описание текста')),
                ('image_about', models.ImageField(upload_to='image_about/', verbose_name='Мое фото')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Oбо мне',
            },
        ),
    ]
