# Generated by Django 4.2.4 on 2023-08-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='text_about',
            field=models.CharField(max_length=500, verbose_name='Описание текста'),
        ),
    ]
