# Generated by Django 4.2.4 on 2023-08-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_me_text_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_me',
            new_name='About',
        ),
    ]
