# Generated by Django 4.2.4 on 2023-08-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_portfolo', models.CharField(max_length=100, verbose_name='Названия фото')),
                ('image_portfolio', models.ImageField(upload_to='portfolio_image/', verbose_name='Фото портфолио')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Добавление портфолио',
            },
        ),
    ]
