# Generated by Django 4.2.3 on 2023-08-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_video_photo_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio_video',
            new_name='Project_video',
        ),
    ]
