# Generated by Django 4.2.3 on 2023-08-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_portfolio_video_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_video',
            name='video_profile',
            field=models.URLField(verbose_name='Видео портфолио'),
        ),
    ]
