# Generated by Django 4.2.3 on 2023-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_video_video_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_video',
            name='video_profile',
            field=models.FileField(upload_to='vipdeo_portfolio/', verbose_name='Видео портфолио'),
        ),
    ]
