# Generated by Django 4.2.3 on 2023-08-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_video_video_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='descriptions_image',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_video',
            name='descriptions_video',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание видео'),
            preserve_default=False,
        ),
    ]
